export const SAVE_PREFERENCES_SUCCESS = 'SAVE_PREFERENCES_SUCCESS';
export const GET_PREFERENCES_SUCCESS = 'GET_PREFERENCES_SUCCESS';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PROJECT_OWNERS = 'GET_PROJECT_OWNERS';
export const GET_PROJECT_OWNERS_SUCCESS = 'GET_PROJECT_OWNERS_SUCCESS';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
