export const DEMO_ACTION = 'DEMO_ACTION';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR';
export const SAVE_PREFERENCES_SUCCESS = 'SAVE_PREFERENCES_SUCCESS';
export const GET_PREFERENCES_SUCCESS = 'SAVE_PREFERENCES_SUCCESS';
export const GET_PREFERENCES = 'SAVE_PREFERENCES_SUCCESS';
